workflows:
  ionic-capacitor-android:
    name: 24/7 Tele H Android (Release)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.teleh.healthcare"
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Update dependencies and clean
        script: |
          npx cap copy android
          npx cap update android
      - name: Build Android Release APK
        script: |
          cd android
          chmod +x ./gradlew
          # Build release APK (debuggable=false, ProGuard enabled)
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - admin@24x7teleh.com
        notify:
          success: true
          failure: false
  
  ionic-capacitor-android-debug:
    name: 24/7 Tele H Android (Debug)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.teleh.healthcare"
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Update dependencies and clean
        script: |
          npx cap copy android
          npx cap update android
      - name: Build Android Debug
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - admin@24x7teleh.com
        notify:
          success: true
          failure: false

  ionic-capacitor-ios:
    name: 24/7 Tele H iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.teleh.healthcare
      vars:
        BUNDLE_ID: "com.teleh.healthcare"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        DEVELOPMENT_TEAM: "BPU9H96U68"
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Update dependencies and clean
        script: |
          npx cap copy ios
          npx cap update ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Create export options
        script: |
          cat > ~/export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.teleh.healthcare</key>
                  <string>TeleH_AppStore</string>
              </dict>
          </dict>
          </plist>
          EOF
      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportOptionsPlist ~/export_options.plist \
            -exportPath $CM_BUILD_DIR/build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - admin@24x7teleh.com
        notify:
          success: true
          failure: false