require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'

end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  
  # Configure linker flags for NeuroSky SDK
  installer.pods_project.targets.each do |target|
    if target.name == 'App'
      target.build_configurations.each do |config|
        config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
        config.build_settings['OTHER_LDFLAGS'] << '-lNSKAlgoSDKECG'
        config.build_settings['LIBRARY_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['LIBRARY_SEARCH_PATHS'] << '$(PROJECT_DIR)/App/Libraries/NeuroSky'
        config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = '$(PROJECT_DIR)/App/Plugins/HC03Bluetooth/HC03Bluetooth-Bridging-Header.h'
      end
    end
  end
end
